
general:
  screenRes: [1680,1050]
  screenRes_HD: [1920,1080]
  screen_distance: 225
  screen_width: 69

  TR: 1.6

  subs: [1,2,3,4,5,7,8,9,11,12,13]

  HD_screen_subs: [2,11,12,13]

  exclude_subs: [3,5,7,13]

  tasks: ['prf','soma']

  paths:
    data: 
      sourcedata: '/Volumes/Verissimo_Seagate_Hub_Plus/Projects/Visuomotor/Data/sourcedata'
      derivatives: '/Volumes/Verissimo_Seagate_Hub_Plus/Projects/Visuomotor/Data/derivatives'

    analysis: '/Users/verissimo/Documents/Projects/Visuomotor_prefrontal/Visuomotor/analysis'

    fitting:
      where: 'local' #'local' #'cartesius' # where to fit, name of machine to get paths from (as specified below)

      cartesius:
        basedir: '/home/inesv/'
        derivatives: '/home/inesv/Visuomotor/Data/derivatives'

      lisa:
        basedir: '/home/inesv/'
        derivatives: '/scratch/Visuomotor_data/Data/derivatives'
        data_dir: '/home/inesv/Visuomotor_data'

      local:
        basedir: '/Users/verissimo/Documents/Projects/Visuomotor_prefrontal/Visuomotor'
        derivatives: '/Volumes/Verissimo_Seagate_Hub_Plus/Projects/Visuomotor/Data/derivatives'


processing:

  space: 'fsaverage' #'T1w'
  extension: '.func.gii'

  sg_filt_window_length: 81
  sg_filt_polyorder: 3
  sg_filt_deriv: 0

  smooth_fwhm: 2

  crop_pRF_TR: 7

  regress_conf: False

  nuisance_columns: ['csf',
                    'white_matter',
                    'global_signal',
                    'std_dvars',
                    'dvars',
                    'framewise_displacement',
                    't_comp_cor_00',
                    't_comp_cor_01',
                    't_comp_cor_02',
                    't_comp_cor_03',
                    't_comp_cor_04',
                    't_comp_cor_05',
                    'a_comp_cor_00',
                    'a_comp_cor_01',
                    'a_comp_cor_02',
                    'a_comp_cor_03',
                    'a_comp_cor_04',
                    'a_comp_cor_05',
                    'trans_x',
                    'trans_y',
                    'trans_z',
                    'rot_x',
                    'rot_x',
                    'rot_z']

eyetracking:

  HP_pupil_f: 0.01
  LP_pupil_f: 6.0
  sampling_freq: 1000

  sacc_thresh: 5 #6 # lambda, median-based standard deviations from the median estimator
  minimum_saccade_duration: 0.006 # 0.016 # minimum duration to consider saccade (ms)

plotting:

  prf:
    rsq_threshold: 0.17 #0.14 #0.17

    n_bins: 10
    min_ecc: 0.25
    max_ecc: 3.3

    ROIs: ['V1','V2','V3','V3AB','hV4','LO','IPS0','IPS1','IPS2+','sPCS','iPCS']

    occipital: ['V1','V2','V3','V3AB','hV4','LO']
    parietal: ['IPS0','IPS1','IPS2+']
    frontal: ['sPCS','iPCS']

    n_TR: 83 # after cropping (original 90)

  soma:
    z_threshold: 3.1 #2.7

    n_TR: 141


fitting:
  prf:
    fit_model: 'gauss' #'css'

    type: 'loo_run' #'median' # type of fitting to do, if leave-one-run-out or average runs and fit on median

    min_eccen: 0.2
    max_eccen: 15

    min_size: 0.2
    max_size: 10

    min_n: 0.01
    max_n: 1.1

    grid_steps: 40

    N_PROCS: 4
    total_chunks: 83

    fit_smooth: False
    extension: 'cropped_sg_psc.func.gii'

  soma:
    fit_smooth: False
    extension: 'sg_psc.func.gii'

    type: 'loo_run' #'median' # type of fitting to do, if leave-one-run-out or average runs and fit on median

    all_contrasts:
      face: ['eyebrows',
            'eyes',
            'mouth',
            'tongue']

      upper_limb: ['lhand_fing1',
                  'lhand_fing2',
                  'lhand_fing3',
                  'lhand_fing4',
                  'lhand_fing5',
                  'rhand_fing1',
                  'rhand_fing2',
                  'rhand_fing3',
                  'rhand_fing4',
                  'rhand_fing5']

      lower_limb: ['lleg',
                  'rleg']

    soma_stimulus: ['eyebrows.avi',
                    'eyes.avi',
                    'mouth.avi',
                    'tongue.avi',
                    'lhand_fing1.avi',
                    'lhand_fing2.avi',
                    'lhand_fing3.avi',
                    'lhand_fing4.avi',
                    'lhand_fing5.avi',
                    'lleg.avi',
                    'eyebrows.avi',
                    'eyes.avi',
                    'mouth.avi',
                    'tongue.avi',
                    'bhand_fing1.avi',
                    'bhand_fing2.avi',
                    'bhand_fing3.avi',
                    'bhand_fing4.avi',
                    'bhand_fing5.avi',
                    'bleg.avi',
                    'tongue.avi',
                    'mouth.avi',
                    'eyes.avi',
                    'eyebrows.avi',
                    'rhand_fing1.avi',
                    'rhand_fing2.avi',
                    'rhand_fing3.avi',
                    'rhand_fing4.avi',
                    'rhand_fing5.avi',
                    'rleg.avi',
                    'eyebrows.avi',
                    'eyes.avi',
                    'mouth.avi',
                    'tongue.avi',
                    'lhand_fing5.avi',
                    'lhand_fing4.avi',
                    'lhand_fing3.avi',
                    'lhand_fing2.avi',
                    'lhand_fing1.avi',
                    'lleg.avi',
                    'eyebrows.avi',
                    'eyes.avi',
                    'mouth.avi',
                    'tongue.avi',
                    'bhand_fing5.avi',
                    'bhand_fing4.avi',
                    'bhand_fing3.avi',
                    'bhand_fing2.avi',
                    'bhand_fing1.avi',
                    'bleg.avi',
                    'tongue.avi',
                    'mouth.avi',
                    'eyes.avi',
                    'eyebrows.avi',
                    'rhand_fing5.avi',
                    'rhand_fing4.avi',
                    'rhand_fing3.avi',
                    'rhand_fing2.avi',
                    'rhand_fing1.avi',
                    'rleg.avi']




