
general:
  screenRes: [1680,1050]
  screenRes_HD: [1920,1080]
  screen_distance: 225
  screen_width: 69

  TR: 1.6

  subs: [1,2,3,4,5,7,8,9,11,12,13]

  HD_screen_subs: [2,11,12,13]

  exclude_subs: [3,5,7,13]

  tasks: ['prf','soma']

  paths:
    local:
      root: '/Volumes/Verissimo_Seagate_Hub_Plus/Projects/Visuomotor/Data'
    lisa:
      root: '/project/projects_verissimo/Visuomotor_data'

prf:
  PRF_ITI_in_TR: 0.5
  bar_pass_in_TRs:
    empty: 10
    L-R: 18
    R-L: 18
    U-D: 10
    D-U: 10

  bar_pass_direction: ['empty','U-D','R-L','empty','L-R','D-U','empty'] 

soma:
  event_dur_in_sec:
    iti: .5
    empty: 12
    stim: 2.25

  trial_order: ['iti','stim', 'iti']

  n_TR: 141

processing:
  space: 'fsaverage' #'T1w'
  file_ext: '.func.gii'

  crop_TR: 
    soma: 0
    prf: 4

  filter:
    soma: 'sg'
    prf: 'dc'

  first_modes_to_remove: 5 # Number of low-frequency eigenmodes to remove (highpass)

  sg_filt_window_length: 81
  sg_filt_polyorder: 3
  sg_filt_deriv: 0

  smooth_fwhm: 2

eyetracking:

  HP_pupil_f: 0.01
  LP_pupil_f: 6.0
  sampling_freq: 1000

  sacc_thresh: 5 #6 # lambda, median-based standard deviations from the median estimator
  minimum_saccade_duration: 0.006 # 0.016 # minimum duration to consider saccade (ms)

plotting:

  prf:
    rsq_threshold: 0.17 #0.14 

    n_bins: 10
    min_ecc: 0.25
    max_ecc: 3.3

    ROIs: ['V1','V2','V3','V3AB','hV4','LO','IPS0','IPS1','IPS2+','sPCS','iPCS']

    occipital: ['V1','V2','V3','V3AB','hV4','LO']
    parietal: ['IPS0','IPS1','IPS2+']
    frontal: ['sPCS','iPCS']

    n_TR: 86 # after cropping (original 90)

  soma:
    glasser_rois:
      M1: ['4'] # primary motor cortex (Brodmann area 4)
      S1: ['3a', '3b', '1', '2'] #['3b'] #['3a', '3b', '1'] # primary sensory cortex (Brodman area 3) 
      SMA: ['6mp', '6ma', 'SCEF'] # supplementary motor areas?
      CingMA: ['24dd', '24dv'] # cingulate motor cortex
      sPMC: ['6d', '6a'] # superior premotor areas
      iPMC: ['6v', '6r'] # inferior premotor areas
      others: ['FEF', 'PEF', '55b']

    gross_regions: # as defined in the SG creatures paper (2020)
      parietal: ['3a', '3b', '1', '2', 'PFt', 'PFop', 'AIP', '7PC', 
                '7AL', 'LIPv', 'VIP', '7Am', 'PF', '7PL', 'MIP']
      frontal: ['4', '6d', '6mp', '6v', 'FEF', '6a', '6ma', '6r', '55b', 'PEF']
      medial: ['5m', '5L', '24dd', '5mv', 'SCEF', '24dv', '23c', 'p24pr']
      operculum_insular: ['43', 'OP1', 'OP4', 'PFcm', 'FOP1', 'OP2‐3',
                          'RI', 'FOP2', 'FOP3', 'Ig', 'A1', 'PSL', 'LBelt',
                          'PBelt', 'A4', 'Pol1', 'Pol2', '52']

fitting:
  prf:
    fit_model: 'gauss' #'css'
    optimizer: 'L-BFGS-B'

    type: 'mean' #'loo_run' #'median' # type of fitting to do, if leave-one-run-out or average runs and fit on median

    extension: 'cropped_dc_psc.func.gii'

    fit_hrf: False #True

    total_chunks: 83

    min_eccen: 0.2
    max_eccen: 15

    min_size: 0.2
    max_size: 10

    min_n: 0.01
    max_n: 1.1

    grid_steps: 40

  soma:
    glm_single_ops:
      hrf: 'canonical' # 'average' # 'fit'
      denoise: True
      fracr: True

    extension: 'sg_psc.func.gii'

    z_threshold: 3.1 #2.7

    type: 'mean' #'loo_run' #'median' # type of fitting to do, if leave-one-run-out or average runs and fit on median

    all_contrasts:
      face: ['eyebrows',
            'eyes',
            'mouth',
            'tongue']

      upper_limb: ['lhand_fing1',
                  'lhand_fing2',
                  'lhand_fing3',
                  'lhand_fing4',
                  'lhand_fing5',
                  'rhand_fing1',
                  'rhand_fing2',
                  'rhand_fing3',
                  'rhand_fing4',
                  'rhand_fing5',
                  'bhand_fing1',
                  'bhand_fing2',
                  'bhand_fing3',
                  'bhand_fing4',
                  'bhand_fing5']

      lower_limb: ['lleg',
                  'rleg',
                  'bleg']

    soma_stimulus: ['eyebrows.avi',
                    'eyes.avi',
                    'mouth.avi',
                    'tongue.avi',
                    'lhand_fing1.avi',
                    'lhand_fing2.avi',
                    'lhand_fing3.avi',
                    'lhand_fing4.avi',
                    'lhand_fing5.avi',
                    'lleg.avi',
                    'eyebrows.avi',
                    'eyes.avi',
                    'mouth.avi',
                    'tongue.avi',
                    'bhand_fing1.avi',
                    'bhand_fing2.avi',
                    'bhand_fing3.avi',
                    'bhand_fing4.avi',
                    'bhand_fing5.avi',
                    'bleg.avi',
                    'tongue.avi',
                    'mouth.avi',
                    'eyes.avi',
                    'eyebrows.avi',
                    'rhand_fing1.avi',
                    'rhand_fing2.avi',
                    'rhand_fing3.avi',
                    'rhand_fing4.avi',
                    'rhand_fing5.avi',
                    'rleg.avi',
                    'eyebrows.avi',
                    'eyes.avi',
                    'mouth.avi',
                    'tongue.avi',
                    'lhand_fing5.avi',
                    'lhand_fing4.avi',
                    'lhand_fing3.avi',
                    'lhand_fing2.avi',
                    'lhand_fing1.avi',
                    'lleg.avi',
                    'eyebrows.avi',
                    'eyes.avi',
                    'mouth.avi',
                    'tongue.avi',
                    'bhand_fing5.avi',
                    'bhand_fing4.avi',
                    'bhand_fing3.avi',
                    'bhand_fing2.avi',
                    'bhand_fing1.avi',
                    'bleg.avi',
                    'tongue.avi',
                    'mouth.avi',
                    'eyes.avi',
                    'eyebrows.avi',
                    'rhand_fing5.avi',
                    'rhand_fing4.avi',
                    'rhand_fing3.avi',
                    'rhand_fing2.avi',
                    'rhand_fing1.avi',
                    'rleg.avi']




